server:
  port: 8080
spring:
  ##  ˝æ›ø‚≈‰÷√
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:log4jdbc:mysql://127.0.0.1:3306/project?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false&serverTimezone=UTC&useSSL=true
    username: root
    password: root
    driver-class-name: net.sf.log4jdbc.DriverSpy
    hikari:
      connection-test-query: select 'x'
      idle-timeout: 60000
      maximum-pool-size: 100
      minimum-idle: 5
